project:
  type: website
  output-dir: docs

website:
  title: "Cathal Mee"
  favicon: "Images/fav.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    code-fold: show

editor: visual

